apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  namesace: openshift-config
spec:
  identityProviders:
  - name: htpasswd_provider
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret